package provider

import (
	"context"
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// An email intake address turns inbound mail into issues. The address itself is
// generated by Linear, not chosen — `address` is computed, and the manageable
// part is the auto-reply behaviour around it.
var emailIntakeAddressEntity = entity{
	name: "emailIntakeAddress",
	fields: `id address enabled type senderName forwardingEmailAddress
		repliesEnabled reopenOnReply useUserNamesInReplies customerRequestsEnabled
		issueCreatedAutoReply issueCreatedAutoReplyEnabled
		issueCompletedAutoReply issueCompletedAutoReplyEnabled
		issueCanceledAutoReply issueCanceledAutoReplyEnabled
		team { id } template { id }`,
}

// NewEmailIntakeAddressResource returns a new linear_email_intake_address resource.
func NewEmailIntakeAddressResource() resource.Resource {
	return &standardResource{
		entity:   emailIntakeAddressEntity,
		typeName: "email_intake_address",
		kind:     "email intake address",
		schema:   emailIntakeAddressSchema,
		newModel: func() crudModel { return &emailIntakeAddressModel{} },
	}
}

type emailIntakeAddressAttributes struct {
	ID      string `json:"id"`
	Address string `json:"address"`
	Enabled bool   `json:"enabled"`
	Type    string `json:"type"`

	SenderName             *string `json:"senderName"`
	ForwardingEmailAddress *string `json:"forwardingEmailAddress"`

	RepliesEnabled          bool `json:"repliesEnabled"`
	ReopenOnReply           bool `json:"reopenOnReply"`
	UseUserNamesInReplies   bool `json:"useUserNamesInReplies"`
	CustomerRequestsEnabled bool `json:"customerRequestsEnabled"`

	IssueCreatedAutoReply          *string `json:"issueCreatedAutoReply"`
	IssueCreatedAutoReplyEnabled   bool    `json:"issueCreatedAutoReplyEnabled"`
	IssueCompletedAutoReply        *string `json:"issueCompletedAutoReply"`
	IssueCompletedAutoReplyEnabled bool    `json:"issueCompletedAutoReplyEnabled"`
	IssueCanceledAutoReply         *string `json:"issueCanceledAutoReply"`
	IssueCanceledAutoReplyEnabled  bool    `json:"issueCanceledAutoReplyEnabled"`

	Team     *ref `json:"team"`
	Template *ref `json:"template"`
}

type emailIntakeAddressModel struct {
	ID      types.String `tfsdk:"id"`
	Address types.String `tfsdk:"address"`
	Enabled types.Bool   `tfsdk:"enabled"`
	Type    types.String `tfsdk:"type"`

	TeamID     types.String `tfsdk:"team_id"`
	TemplateID types.String `tfsdk:"template_id"`

	SenderName             types.String `tfsdk:"sender_name"`
	ForwardingEmailAddress types.String `tfsdk:"forwarding_email_address"`

	RepliesEnabled          types.Bool `tfsdk:"replies_enabled"`
	ReopenOnReply           types.Bool `tfsdk:"reopen_on_reply"`
	UseUserNamesInReplies   types.Bool `tfsdk:"use_user_names_in_replies"`
	CustomerRequestsEnabled types.Bool `tfsdk:"customer_requests_enabled"`

	IssueCreatedAutoReply          types.String `tfsdk:"issue_created_auto_reply"`
	IssueCreatedAutoReplyEnabled   types.Bool   `tfsdk:"issue_created_auto_reply_enabled"`
	IssueCompletedAutoReply        types.String `tfsdk:"issue_completed_auto_reply"`
	IssueCompletedAutoReplyEnabled types.Bool   `tfsdk:"issue_completed_auto_reply_enabled"`
	IssueCanceledAutoReply         types.String `tfsdk:"issue_canceled_auto_reply"`
	IssueCanceledAutoReplyEnabled  types.Bool   `tfsdk:"issue_canceled_auto_reply_enabled"`
}

func (m *emailIntakeAddressModel) id() string { return m.ID.ValueString() }

func (m *emailIntakeAddressModel) decode(_ context.Context, raw json.RawMessage) error {
	var a emailIntakeAddressAttributes
	if err := json.Unmarshal(raw, &a); err != nil {
		return err
	}
	m.ID = types.StringValue(a.ID)
	m.Address = types.StringValue(a.Address)
	m.Enabled = types.BoolValue(a.Enabled)
	m.Type = types.StringValue(a.Type)

	m.SenderName = types.StringPointerValue(a.SenderName)
	m.ForwardingEmailAddress = types.StringPointerValue(a.ForwardingEmailAddress)

	m.RepliesEnabled = types.BoolValue(a.RepliesEnabled)
	m.ReopenOnReply = types.BoolValue(a.ReopenOnReply)
	m.UseUserNamesInReplies = types.BoolValue(a.UseUserNamesInReplies)
	m.CustomerRequestsEnabled = types.BoolValue(a.CustomerRequestsEnabled)

	m.IssueCreatedAutoReply = types.StringPointerValue(a.IssueCreatedAutoReply)
	m.IssueCreatedAutoReplyEnabled = types.BoolValue(a.IssueCreatedAutoReplyEnabled)
	m.IssueCompletedAutoReply = types.StringPointerValue(a.IssueCompletedAutoReply)
	m.IssueCompletedAutoReplyEnabled = types.BoolValue(a.IssueCompletedAutoReplyEnabled)
	m.IssueCanceledAutoReply = types.StringPointerValue(a.IssueCanceledAutoReply)
	m.IssueCanceledAutoReplyEnabled = types.BoolValue(a.IssueCanceledAutoReplyEnabled)

	m.TeamID = refID(a.Team)
	m.TemplateID = refID(a.Template)
	return nil
}

func (m *emailIntakeAddressModel) input(_ context.Context, forUpdate bool) map[string]any {
	in := map[string]any{}
	putString(in, "teamId", m.TeamID, false)
	putString(in, "templateId", m.TemplateID, forUpdate)
	putString(in, "senderName", m.SenderName, forUpdate)
	putString(in, "forwardingEmailAddress", m.ForwardingEmailAddress, forUpdate)

	putBool(in, "repliesEnabled", m.RepliesEnabled, false)
	putBool(in, "reopenOnReply", m.ReopenOnReply, false)
	putBool(in, "useUserNamesInReplies", m.UseUserNamesInReplies, false)
	putBool(in, "customerRequestsEnabled", m.CustomerRequestsEnabled, false)

	putString(in, "issueCreatedAutoReply", m.IssueCreatedAutoReply, forUpdate)
	putBool(in, "issueCreatedAutoReplyEnabled", m.IssueCreatedAutoReplyEnabled, false)
	putString(in, "issueCompletedAutoReply", m.IssueCompletedAutoReply, forUpdate)
	putBool(in, "issueCompletedAutoReplyEnabled", m.IssueCompletedAutoReplyEnabled, false)
	putString(in, "issueCanceledAutoReply", m.IssueCanceledAutoReply, forUpdate)
	putBool(in, "issueCanceledAutoReplyEnabled", m.IssueCanceledAutoReplyEnabled, false)

	// `type` only exists on the create input; `enabled` only on the update one.
	if forUpdate {
		putBool(in, "enabled", m.Enabled, false)
	} else {
		putString(in, "type", m.Type, false)
	}
	return in
}

func emailIntakeAddressSchema() schema.Schema {
	optBool := func(desc string) schema.Attribute {
		return schema.BoolAttribute{MarkdownDescription: desc, Optional: true, Computed: true}
	}

	return schema.Schema{
		MarkdownDescription: "Manages a Linear email intake address — the mailbox inbound mail becomes issues " +
			"through, together with the auto-replies sent back.\n\n" +
			"The address itself is generated by Linear rather than chosen, so `address` is read-only.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "UUID of the intake address.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"address": schema.StringAttribute{
				MarkdownDescription: "The generated email address mail is sent to.",
				Computed:            true,
			},
			"team_id": schema.StringAttribute{
				MarkdownDescription: "UUID of the team incoming mail creates issues for.",
				Optional:            true,
			},
			"type": schema.StringAttribute{
				MarkdownDescription: "Kind of intake address — e.g. `team`, `template`, `asks`. Changing it " +
					"replaces the resource, since the update mutation has no `type`.",
				Optional:      true,
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
			},
			"template_id": schema.StringAttribute{
				MarkdownDescription: "UUID of the `linear_template` incoming issues are created from.",
				Optional:            true,
			},
			"enabled": optBool("Whether the address accepts mail."),
			"sender_name": schema.StringAttribute{
				MarkdownDescription: "Name auto-replies are sent under.",
				Optional:            true,
			},
			"forwarding_email_address": schema.StringAttribute{
				MarkdownDescription: "Address mail is forwarded from, when the intake sits behind another mailbox.",
				Optional:            true,
			},

			"replies_enabled":           optBool("Whether replies on the thread are pulled back into the issue."),
			"reopen_on_reply":           optBool("Whether a reply reopens a closed issue."),
			"use_user_names_in_replies": optBool("Whether replies are attributed to the responding member by name."),
			"customer_requests_enabled": optBool("Whether inbound mail also creates customer requests. Needs " +
				"Linear Customers enabled for the workspace."),

			"issue_created_auto_reply": schema.StringAttribute{
				MarkdownDescription: "Auto-reply sent when the issue is created.",
				Optional:            true,
			},
			"issue_created_auto_reply_enabled": optBool("Whether the created auto-reply is sent."),
			"issue_completed_auto_reply": schema.StringAttribute{
				MarkdownDescription: "Auto-reply sent when the issue is completed.",
				Optional:            true,
			},
			"issue_completed_auto_reply_enabled": optBool("Whether the completed auto-reply is sent."),
			"issue_canceled_auto_reply": schema.StringAttribute{
				MarkdownDescription: "Auto-reply sent when the issue is canceled.",
				Optional:            true,
			},
			"issue_canceled_auto_reply_enabled": optBool("Whether the canceled auto-reply is sent."),
		},
	}
}
